### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by SunSDSE** [dhesant/apcups2telegraf#1]
Good Day, 
The data that should be collected looks like: 
$ upsc ups@cyva:3493
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 50
battery.runtime: 240
battery.runtime.low: 120
battery.type: PbAc
battery.voltage: 27.3
battery.voltage.nominal: 24.0
device.mfr: American Power Conversion
device.model: Smart-UPS 1500
device.serial: AS1144110414  
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 5
driver.parameter.port: auto
driver.version: DSM6-2-25510-201118
driver.version.data: APC HID 0.95
driver.version.internal: 0.38
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.firmware: UPS 06.5 / ID=18
ups.mfr: American Power Conversion
ups.mfr.date: 2011/10/26
ups.model: Smart-UPS 1500
ups.productid: 0003
ups.serial: AS1144110414  
ups.status: OL
ups.timer.reboot: -1
ups.timer.shutdown: -1
ups.vendorid: 051d

2022-06-03T00:05:10Z W! [inputs.apcupsd] Collection took longer than expected; not complete after interval of 10s
panic: runtime error: index out of range [0] with length 0
goroutine 89 [running]:
github.com/influxdata/telegraf/plugins/inputs/apcupsd.(*ApcUpsd).Gather.func1({0x51f6b58, 0x8d28000}, 0x93ea7e0, {0x52036b8, 0x8fdae88}, {0x93f8661, 0x1e})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/apcupsd/apcupsd.go:71 +0xb90
github.com/influxdata/telegraf/plugins/inputs/apcupsd.(*ApcUpsd).Gather(0x93ea7e0, {0x52036b8, 0x8fdae88})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/apcupsd/apcupsd.go:96 +0x94
github.com/influxdata/telegraf/models.(*RunningInput).Gather(0x93e84e0, {0x52036b8, 0x8fdae88})
	/go/src/github.com/influxdata/telegraf/models/running_input.go:118 +0x48
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1()
	/go/src/github.com/influxdata/telegraf/agent/agent.go:487 +0x34
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
	/go/src/github.com/influxdata/telegraf/agent/agent.go:486 +0xe4

**Comment by SunSDSE** [comment]
Additional Details. 
Running in a Docker Swarm.
Telegraf 1.22.4
Welcome to InfluxDB  
version=v2.2.0 
commit=a2f8538837 
build_date=2022-04-06T17:36:38Z

**Comment by SunSDSE** [comment]
I am sorry, You can close this. I was reviewing my configuration and it occurred to me that while I used to use "apcupsd". I ran into limitations with it and migrated to Network UPS Tools (https://github.com/networkupstools/networkupstools.github.io). So your code does not apply.

**Comment by SunSDSE** [comment]
I am sorry, You can close this. I was reviewing my configuration and it occurred to me that while I used to use "apcupsd". I ran into limitations with it and migrated to Network UPS Tools (https://github.com/networkupstools/networkupstools.github.io). So your code does not apply.
